- src: https://opendev.org/openstack/openstack-ansible-galera_server
  scm: git
  name: galera_server

- src: https://opendev.org/openstack/ansible-config_template
  scm: git
  name: config_template

- name: apt_package_pinning
  scm: git
  src: https://opendev.org/openstack/openstack-ansible-apt_package_pinning
