# These do not need to be edited.
db_user: mmmost
db_name: mattermost

mattermost_version: 5.31.0
mattermost_package_url: https://releases.mattermost.com/{{ mattermost_version }}/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz
mattermost_postgres: true
# Choose a secure password. It is recommended you create a random password using
# an external utility.
db_password: notReallyPassword
db_host: 127.0.0.1
db_port: "{{ (mattermost_postgres | bool) | ternary('5432', '3306') }}"
db_driver: "{{ (mattermost_postgres | bool) | ternary('postgres', 'mysql') }}"
db_connection: "{{ (mattermost_postgres | bool) | ternary(db_host ~ ':' ~ db_port, 'tcp(' ~ db_host ~ ':' ~ db_port ~ ')') }}"
db_postgres_options: "sslmode=disable&connect_timeout=10"
db_mysql_options: "charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"

mattermost_special:
  - config
  - plugins
  - client/plugins
  - data

mattermost_mount_src: ""
mattermost_mount_type: "nfs"
mattermost_mount_options: "_netdev,auto"
mattermost_mount_credentials: ''
